#Copyright IBM Corp. All Rights Reserved.
#SPDX-License-Identifier: Apache-2.0

[[constraint]]
  version = "0.18.0"
  name = "github.com/hyperledger/burrow"

[[constraint]]
  branch = "master"
  name = "github.com/hyperledger/fabric"

[[constraint]]
  branch = "master"
  name = "github.com/onsi/ginkgo"

[[constraint]]
  branch = "master"
  name = "github.com/onsi/gomega"

[[override]]
  version = "~0.6.0"
  name = "github.com/tendermint/tmlibs"

[[override]]
  revision = "57142e89befe90977da6dce7762f9fcc70f28da1"
  name = "github.com/docker/docker"

[prune]
  go-tests = true
  unused-packages = true
